batch_size: 256
clip_gradient_norm: 1
clip_targets_to_zero:
- QObs_CAMELS(mm/h)
commit_hash:
data_dir: /home/ottersloth/data/camels_hourly
dataset: hourly_camels_us
device: cpu
dynamic_inputs:
- total_precipitation
- temperature
epochs: 3
experiment_name: test_run_hourly
forcings:
- nldas_hourly
head: regression
hidden_size: 20
img_log_dir: /home/ottersloth/neuralhydrology/run_hourly/runs/test_run_hourly_2806_222735/img_log
initial_forget_bias: 3
learning_rate:
  0: 0.01
  30: 0.005
  40: 0.001
log_interval: 5
log_n_figures: 1
log_tensorboard: true
loss: MSE
metrics:
- NSE
model: cudalstm
num_workers: 8
number_of_basins: 1
optimizer: Adam
output_activation: linear
output_dropout: 0.4
package_version: 1.3.0
predict_last_n: 1
run_dir: /home/ottersloth/neuralhydrology/run_hourly/runs/test_run_hourly_2806_222735
save_weights_every: 1
seed: 593910
seq_length: 336
target_variables:
- QObs_CAMELS(mm/h)
test_basin_file: 1_basin.txt
test_end_date: 30/09/1999
test_start_date: 01/10/1989
train_basin_file: 1_basin.txt
train_dir: /home/ottersloth/neuralhydrology/run_hourly/runs/test_run_hourly_2806_222735/train_data
train_end_date: 30/09/2003
train_start_date: 01/10/2000
validate_every: 1
validate_n_random_basins: 1
validation_basin_file: 1_basin.txt
validation_end_date: 30/09/1989
validation_start_date: 01/10/1987
