batch_size: 256
clip_gradient_norm: 1
clip_targets_to_zero:
- QObs_CAMELS(mm/h)
commit_hash:
data_dir: /home/ottersloth/data/camels_hourly
dataset: hourly_camels_us
device: cpu
dynamic_inputs:
- total_precipitation
- longwave_radiation
- shortwave_radiation
- pressure
- specific_humidity
- temperature
- wind_u
- wind_v
epochs: 1
experiment_name: fold_0
forcings:
- nldas_hourly
head: regression
hidden_size: 256
img_log_dir: /home/ottersloth/neuralhydrology/nextgen-form-eval/run_hourly/runs/fold_0_0407_235730/img_log
initial_forget_bias: 3
learning_rate:
  0: 4e-05
log_interval: 5
log_n_figures: 1
log_tensorboard: true
loss: NSE
metrics:
- NSE
model: cudalstm
num_workers: 8
number_of_basins: 464
optimizer: Adam
output_activation: linear
output_dropout: 0.4
package_version: 1.3.0
predict_last_n: 1
run_dir: /home/ottersloth/neuralhydrology/nextgen-form-eval/run_hourly/runs/fold_0_0407_235730
save_weights_every: 1
seed: 584059
seq_length: 4320
static_attributes:
- elev_mean
- slope_mean
- area_gages2
- frac_forest
- lai_max
- lai_diff
- gvf_max
- gvf_diff
- soil_depth_pelletier
- soil_depth_statsgo
- soil_porosity
- soil_conductivity
- max_water_content
- sand_frac
- silt_frac
- clay_frac
- carbonate_rocks_frac
- geol_permeability
- p_mean
- pet_mean
- aridity
- frac_snow
- high_prec_freq
- high_prec_dur
- low_prec_freq
- low_prec_dur
target_variables:
- QObs_CAMELS(mm/h)
test_basin_file: Basin_CV_Splits/basins_test_0.txt
test_end_date: 30/09/2008
test_start_date: 01/10/2003
train_basin_file: Basin_CV_Splits/basins_train_0.txt
train_dir: /home/ottersloth/neuralhydrology/nextgen-form-eval/run_hourly/runs/fold_0_0407_235730/train_data
train_end_date: 30/09/2013
train_start_date: 01/10/2008
validate_every: 10000
validate_n_random_basins: 1
validation_basin_file: 1_basin.txt
validation_end_date: 30/09/2006
validation_start_date: 01/10/2004
