xarray_feature_scale:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    QObs_CAMELS(mm/h):
      dims: []
      attrs: {}
      data: 0.09811898320913315
    temperature:
      dims: []
      attrs: {}
      data: 10.819310188293457
    total_precipitation:
      dims: []
      attrs: {}
      data: 0.5182175040245056
xarray_feature_center:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    QObs_CAMELS(mm/h):
      dims: []
      attrs: {}
      data: 0.051832590252161026
    temperature:
      dims: []
      attrs: {}
      data: 7.160574436187744
    total_precipitation:
      dims: []
      attrs: {}
      data: 0.11279862374067307
